# Site settings
title:          Matthew Warman
description:    "Technical Swiss Army Knife"
baseurl:        "/blog"
url:            "https://warman.io"

# Author
author:
  name:         Matthew Warman
  url:          https://warman.io
  email:        mcwarman@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
