version: '3'
services:
  mcwarman.github.io:
    build:
      context: .
      dockerfile: dockerfile
    image: mcwarman.github.io_blog:latest
    container_name: mcwarman.github.io_blog
    hostname: jekyll
    ports:
      - '127.0.0.1:4000:4000'
    volumes:
      - .:/srv/jekyll
    command: ["jekyll", "server", "--config", "_config.yaml,_config_dev.yaml", "--watch", "--force_polling" , "--drafts"]
